### ISSUE TITLE
TrackMouseEvent problem

### ISSUE THREAD

**Issue by ghswebguy** [iswix-llc/iswix#10]
![image](https://user-images.githubusercontent.com/30117122/52435043-c9e75c80-2ade-11e9-9d90-8ed003e9781d.png)
[iswixerror.txt](https://github.com/iswix-llc/iswix/files/2842295/iswixerror.txt)

I had been using IsWix sucessfully for a few months now, and has really helped me with the quick adoption of the Wix due to the GUI interface.  On Thursday of last week it started throwing this error whenever I opened it.  I've tried installing the newer version.  I uninstalled and re-installed the newest version, but still getting the same error.

Any insight into what's happening here?

**Comment by chrpai** [comment]
Sorry, I just saw this issue.  I've never seen this error before.  Are you still getting it?   What are you doing when it happens?   FWIW  I've been moving IsWiX to WPF instead of Winforms so maybe the latest release that I just published will incidentally fix this issue for you.  Let me know your results and I'll do whatever I can for you.

**Comment by cptyler** [comment]
https://social.msdn.microsoft.com/Forums/en-US/739f4595-1a2c-4fea-a29f-8924c6609a58/systemaccessibilityimprovementsuselegacyaccessibilityfeatures-error?forum=winforms

It appears there is an issue between the Telerik JustMock profiler and the latest Visual Studio update that causes this.  I am not sure that it is the answer, but is definitely an answer.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by ghswebguy** [comment]
This was the fix.  I disabled the Telerik JustMock Profiler and now I don't have the issue anymore.

**Comment by chrpai** [comment]
Thanks @cptyler    @ghswebguy  do you mind upgrading to the new WPF version at some point and retesting?   I still have some WinForms user controls  so I'm curious to know if this makes any different.
