### ISSUE TITLE
Several designers not visible

### ISSUE THREAD

**Issue by IMFTool** [iswix-llc/iswix#18]
I have installed IsWiX-4.14.5.0.msi on Win 10 Pro (as Parallels VM on a Mac Catalina host).
The IsWix GUI does not show the following designers:
Files and Folders
Services
Shortcuts
I have also tried IsWiX-4.14.4.0.msi, same thing.
Any hint would be welcome.

**Comment by chrpai** [comment]
Those three designers only appears for wxs fragments containing the Module element. It isn't designed to work within the context of a Product or Fragment element.  Other designers such as the Features Designer are coded to only support  authoring Product and Fragment wxs fragments.  Finally some such as the Properties designer will handle any type of document.

You can refer to the main class file of each designer and look at the IsValidContext() method implementation.   When in doubt, use the IsWiX project templates and it will all work easily.  Trying to use IsWiX to update project files not created by the IsWiX scaffolding may have issues.
