### ISSUE TITLE
64 Bit installer

### ISSUE THREAD

**Issue by jkoplo** [iswix-llc/iswix#19]
I'm new to WiX (and IsWix) but I need to package up a ASP.NET Core Service worker. My project is targeting 64 bit, and I found that I can easily set the `Package Platform` to x64. Then I hand editted the Product.wxs Platform to also be x64.

Unfortunately it looks like Wix projects won't accept anything other than x86 in my Project/Solution configuration.

From my research online, it appears I have to manually add `Win64='yes'` to every component? There are 730 components due to the way ASP.NET core is packaging, so this would be less than ideal.

There's got to be an easy solution I'm missing, right?

**Comment by chrpai** [comment]
To make a 64 bit installer just use the IsWiX solution template then change the platform arch on the Setup (.MSI) and Merge Module (.MSM) projects.  Also change the ProgramFilesFolder diretory ID in Features.wxs to ProgramFilesFolder64. 

IsWiX will automatically author the Win64 attribute when the merge module arch is x64.
