### ISSUE TITLE
Adjusting project features

### ISSUE THREAD

**Issue by evgenijbystrov** [iswix-llc/iswix#2]
I entered all fields of ProductFeature. Then I add new one feature. Click on it. Then delete it using context menu. After that I was not able to see parameters of my very first ProductFeature. Fields are not updated.

**Comment by iswix-llc** [comment]
I'll look at this later.  I thought the feature designer working but I haven't used it a while.

Are you using this on wxs generated by the template or  wxs that you already had?   IsWiX is likely to have wierd behavior on hand generated code.

**Comment by iswix-llc** [comment]
For some reason the AfterSelect event was reading the correct element but it wasn't reflecting in the UI.  I changed the code to only delete the node/element and  then select the root node.  At this point AfterSelect fires and everything refreshes.   I really wish this was all written in WPF using MVVM.  I'd rewrite it all if I had the developers and the time.   Thanks for pointing this out and it's now a little bit better then it was before.
