### ISSUE TITLE
Inability to select .NET framework version

### ISSUE THREAD

**Issue by Reahreic** [iswix-llc/iswix#20]
The inability to select a specific version of the .New framework via the project's properties results in erroneous reference warnings for the MM and the inability to compile if the "IsWix Solution for WiX v3" due to a missing preprocessor variable in Features.wxs. The specifically occurs when the IsWix project is added to another solution and not created as it's own standalone solution.

While the docs state to create a new solution, it would be nice to have the ability.

**Comment by chrpai** [comment]
This is a function of the WiX Visual Studio Extension (Votive).  WiX wrote that code and IsWiX just uses a customized project template.  There is nothing I can do about that and one of the reasons that I suggest putting installer code in it's own solution.  (The other 2 big reasons are 1) Votive is frequently late to be updated when a new version of VS comes out 2) It helps ensure that all application projects are build before any installer projects without lots of complicated project dependency / build order configurations. )
