### ISSUE TITLE
Is VS 2022 support planned?

### ISSUE THREAD

**Issue by brisingraerowing** [iswix-llc/iswix#21]
As per title. I'm currently using VS2022 (mostly just testing things), and it works a lot better than 2019 from what I've seen so far.

**Comment by guido-altmann** [comment]
I would also be very happy to receive VS 2022 support.

**Comment by sn4k3** [comment]
I'm also waiting this so i can migrate to VS2022 :D

**Comment by chrpai** [comment]
Sorry, I've been very swamped.  I had been waiting for Votive2022 to ship and lost track. It shipped on 12/26 so I'm about a week behind it seems.

I'll drink a cup of coffee and start tonight.

**Comment by chrpai** [comment]
I made really good progress (99% the way there)  but there is one bug remaining which requires my nuget dependency GlobalParams to fix a VS2022 issue.  I've filed a ticket here. https://github.com/tpalacino/GlobalParams/issues/3

**Comment by chrpai** [comment]
https://github.com/iswix-llc/iswix/releases/tag/v4.15.12

**Comment by chrpai** [comment]
I'm working out some GAC issues that occur on upgrade.  A little more work to do.

**Comment by chrpai** [comment]
Ok I feel a lot better about this release.  Please provide feedback if you see anything. https://github.com/iswix-llc/iswix/releases/tag/v4.15.23

**Comment by guido-altmann** [comment]
Looks good so far. However, the VS language setting is changed by the installer.

**Comment by chrpai** [comment]
I'm not sure how it could do that but then again I'm not multilingual.  Did it do this in VS2019?

**Comment by brisingraerowing** [comment]
The language didn't change for me. @guido-altmann Were you using a language other than English?

**Comment by guido-altmann** [comment]
I have VS (2019 & 2022) installed on a German Windows with German and English language packs for VS. English was set as the default. After installing IsWix, the setting was reset to "Same as Microsoft Windows" (here German).

**Comment by chrpai** [comment]
So we have always called devenv.exe /setup after laying down the extension files.  Can you open a tools prompt for each version and run that command and see if it repeats the problem?

**Comment by chrpai** [comment]
There was a bug in v4.15.23 that causes Visual Studio to crash when you upgrade from v17.0.0 to v17.1.0.  I've shipped a new version of IsWiX that doesn't have this bug.

https://github.com/iswix-llc/iswix/releases/tag/v4.15.34.0

However, if you've already installed v4.15.23 you will need to:

Remove Microsoft.VisualStudio.Interop.dll from the GAC.  (C:\Windows\http://Microsoft.NET\assembly\GAC_MSIL\Microsoft.VisualStudio.Interop\v4.0_17.0.0.0__b03f5f7f11d50a3a)

Run repair on Visual Studio Installer

Install latest version of IsWiX.
