### ISSUE TITLE
An error occurred trying to start process 'https://www.firegiant.com/products/wix-expansion-pack/MSIX/'

### ISSUE THREAD

**Issue by icnocop** [iswix-llc/iswix#26]
IsWiX 5.0.9.0

Run IsWix standalone
1. Open wxs file
2. Click Design View > MSIX
3. Click "The MSIX designer requires the Fire Giant WiX Expansion Pack. Click here for more information"
4. Click "Click here for more information on obtaining the Fire Giant WiX Extension Pack."

The following message occurs:

> [MSIX Requirements]
> Unhandled exception has occurred in a component in your application. If you click Continue, the application will ignore this error and attempt to continue.
> 
> An error occurred trying to start process 'https://www.firegiant.com/products/wix-expansion-pack/MSIX/' with working directory 'C:\Program Files\ISWIX LLC\IsWiX'. The system cannot find the file specified.
> [Details] [Continue]

[Details.txt](https://github.com/iswix-llc/iswix/files/11141105/Details.txt)

**Comment by chrpai** [comment]
This seems to be a .net core migration side effect.  Investigating why launching a url no longer starts the default browser.
