### ISSUE TITLE
"The document is not ready to be saved." when trying to exit the application

### ISSUE THREAD

**Issue by icnocop** [iswix-llc/iswix#27]
IsWiX 5.0.9

1. Launch IsWiX standalone
2. Open a read-only wxs file
3. Try to exit the application

The following message appears:

> The document is not ready to be saved.
> [OK]

Clicking OK does not exit the application, so I have to end the process using Task Manager for example.

**Comment by chrpai** [comment]
This is a function of close wanting to prompt for saving of modified data but the XSD validation fails and blocks everything. Usually it's because of something enterered into Xml Editor or prexisting Xml that is invalid.  I will come up with a better UX.

**Comment by chrpai** [comment]
@icnocop Thank you so much for filing these issues. I've resolved them all.  I see you have an interest in all things WiX and would love to meet virtually for an hour to give you a tour of WiX v4 and IsWiX and answer any questions that you may have.
