### ISSUE TITLE
Problem With Dragging From Source Files TO Destination Files Quadrant

### ISSUE THREAD

**Issue by melvin78** [iswix-llc/iswix#35]
Thanks for a very helpful product . There is part of the documentation

    Click on the [INSTALLLOCATION] folder in the destination view.
    Drag the file WebSite folder from the source files to the destination files quadrant.
    Press Control-S to save the changes back to disk and close the IsWiX application.
    This should cause Visual Studio to detect that the .wxs file was modified out of process. Click Yes to cause it to reload in the IDE.

I was able to do this on the first try but now its not working am not able to drag the files, when i try to drag nothing is happening. Kindly assist
![iswix](https://github.com/iswix-llc/iswix/assets/67906796/a5094492-6494-4f8e-86d2-da359a48dc17)

**Comment by chrpai** [comment]
I've attempted to reproduce your problem by creating a directory structure similiar to your concern but unfortuntaly I'm not experiencing your issue.  I'd suggest creating a video and/or clicking on the destination folder to ensure it is the selected target.

I'd also note that you may wish to drag your source folder down and rename it to website or drag all the files down into website and all the subfolders into website.  Alternatively you can name the folder whatever you like and update the IIS Components wxs accordingly.

![image](https://github.com/iswix-llc/iswix/assets/43178814/f7b534bc-4a83-428f-8b02-0fbc4d15196f)

**Comment by melvin78** [comment]
Hi, i am not sure what happened but on the next restart of my machine the drag feature was working as expected. I will aslo take note of the suggestion you have given i didnt know you could that. Also maybe have you had plans to add custom actions integrated with the UI. Lets say i want to have a custom action where a user has to input a valid activation/product key to continue with the installation. Thanks for the great library once more

**Comment by melvin78** [comment]
Ooo okay i see totally makes sense. But thanks again for the amazing tool !!... Also on a totally unrelated question how can i pass parameters that are keyed in during installation. I am using the IISMeta.wxs to register my IIS websites. I have a requirement that all my webistes should have a hostname. So i also have an install sequence that runs a .bat script to go and the entries in me etc/hosts file. here is a sample
![iis](https://github.com/iswix-llc/iswix/assets/67906796/078d0838-f989-404a-a37b-a8703aa07ca7)

i would like to make the header section dynamic and let it come from user input when installing is it something complicated? possible?

regards
