### ISSUE TITLE
Issues with WixV4 and StandardDirectories

### ISSUE THREAD

**Issue by sean-mcl** [iswix-llc/iswix#36]
Hey,

when I try to use merge modules and use the new wix v4 syntax with the standard directories, folders are missing in the overview and the app becomes instable.

Here is a minimal example:

## .csproj

```
<Project Sdk="WixToolset.Sdk/5.0.0">
  <PropertyGroup>
    <OutputType>Module</OutputType>
  </PropertyGroup>
</Project>
```

## .wxs
```
<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs">
    <Module Id="MergeModule1" Guid="98c6a527-857a-4330-9214-b422b29eb7a1" Language="1033" Version="1.0.0.0">
        <SummaryInformation Manufacturer="TODO Manufacturer" />
        <Directory Id="MergeRedirectFolder">
            <Component Guid="417eb5c7-3622-49c2-838a-aae61e90ee76">
                <File Source="MergeModule.wxs" />
            </Component>
        </Directory>
        <StandardDirectory Id="CommonAppDataFolder">
            <Component Guid="417eb5c7-3622-49c2-838a-aae61e90ee77">
                <File Source="MergeModule.wxs" />
            </Component>
        </StandardDirectory>
        <StandardDirectory Id="CommonFilesFolder">
            <Component Guid="417eb5c7-3622-49c2-838a-aae61e90ee78">
                <File Source="MergeModule.wxs" />
            </Component>
        </StandardDirectory>

    </Module>
</Wix>
```

### Missing directories in overview

![image](https://github.com/iswix-llc/iswix/assets/64470948/74f951b0-2568-4212-939b-652933571039)

### Unhandled Exception on Sort

![image](https://github.com/iswix-llc/iswix/assets/64470948/db61ba09-e644-47b0-9834-02cd0ef276fe)

**Comment by chrpai** [comment]
The files and folders designer for merge modules isn't designed to use standarddirectory elements. It will author the directory entries for you and everything will just work.  Let me know if you'd like a demonstration.

I have fixed the sorting exception.
